### ISSUE TITLE
[feature request] support custom ajv options

### ISSUE THREAD

**Issue by lisuizhe** [apideck-libraries/reva#7]
Thanks for developing this lib. I found this library easiest to use with rich error message, comparing with:
- https://github.com/anttiviljami/openapi-backend
- https://github.com/Gi60s/openapi-enforcer
- https://github.com/Rhosys/openapi-data-validator.js

However, as per title, current reva library has a hard-coded ajv options, please consider supporting custom ajv options like: https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#parameter-optsajvopts-1

**Comment by elsmr** [comment]
Hi @lisuizhe, thanks for your detailed issue and PR contribution! :smile:

Any specific AJV options you'd like to set? I'm not sure if we want to open up all AJV options, users could break the library in unexpected ways.

**Comment by AOEChamp** [comment]
@elsmr I have one usecase. I'd like to configure ajv to use ajv-formats: https://ajv.js.org/packages/ajv-formats.html/

I have an OpenAPI 3.0 spec with `int32` types and by default, ajv throws an error:
```
unknown format "int32" ignored in schema at path
```

**Comment by lisuizhe** [comment]
> Hi @lisuizhe, thanks for your detailed issue and PR contribution! 😄
> 
> Any specific AJV options you'd like to set? I'm not sure if we want to open up all AJV options, users could break the library in unexpected ways.

@elsmr thanks for your reply and sorry for my late response.
In my case I want to use all these 3 options https://ajv.js.org/options.html#options-to-modify-validated-data to modify data during validation

**Comment by elsmr** [comment]
Ok sounds like there are many different use cases to customize the AJV options 😄, let's move forward with PR #8.

Thanks for your feedback @lisuizhe @AOEChamp

**Comment by elsmr** [comment]
Closed by #8, released in [v0.2.0](https://github.com/apideck-libraries/reva/releases/tag/v0.2.0)
